auto: true
pygments: true
server: true
exclude:
- bower_components
- node_modules
- src
- .gitignore
- bower.json
- CNAME
- Gruntfile.js
- package.json

#permalink: /articles/:title
permalink: /:categories/:title
domain: sscank.sconstans.fr
title: Sscank
author: Simon Constans
pseudo: kosssi
githubUrl: https://github.com/kosssi
email: sscank[at]sconstans.fr
